# Generated by Django 4.1.7 on 2023-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
